/****** Script for SelectTopNRows command from SSMS  ******/
SELECT TOP (1000) [PayoutStructureID]
      ,[Name]
      ,[MinPlayers]
      ,[MaxPlayers]
      ,[Position01]
      ,[Position02]
      ,[Position03]
      ,[Position04]
      ,[Position05]
      ,[Position06]
      ,[Position07]
      ,[Position08]
      ,[Position09]
      ,[Position10]
  FROM [WAPL].[dbo].[PayoutStructures]